spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
